---
fallback_driver_version_sles_g06: "580.105.08"
fallback_driver_version_sle_micro_g06: "580.126.16"

fallback_driver_version_sles_g07: "595.58.03"
fallback_driver_version_sle_micro_g07: "595.58.03"
